---

name: Test

on:
  push:
    branches: [latest]
    paths:
      - 'test/**'
      - 'lua/geoip_lookup_w_backend.lua'
      - 'backend/geoip_lookup.py'
      - '.github/workflows/test.yml'
      - '.github/workflows/test_pr.yml'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - haproxy-version: '3.2'
            os: 'ubuntu-24.04'

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt install -y zip software-properties-common >/dev/null

          sudo add-apt-repository -y ppa:vbernat/haproxy-${{ matrix.haproxy-version }} >/dev/null
          sudo apt-get update >/dev/null
          sudo apt-get install -y haproxy >/dev/null
    
          pip install maxminddb >/dev/null
        shell: bash

      - name: Checking HAProxy
        run: |
          set +e
          touch /tmp/haproxy_geoip_country.map /tmp/haproxy_geoip_continent.map /tmp/haproxy_geoip_asn.map /tmp/haproxy_geoip_asname.map
          ln -sf /lua/geoip_lookup_w_backend.lua /tmp/haproxy_geoip_lookup.lua

          timeout 5 haproxy -W -f test/haproxy_test.cfg
          ec="$?"
          if [[ "$ec" != "124" ]]
          then
            exit 1
          fi
        shell: bash

      - name: Checking Python-Backend
        run: |
          set +e
          timeout 5 python backend/geoip_lookup.py
          ec="$?"
          if [[ "$ec" != "124" ]]
          then
            exit 1
          fi
        shell: bash

      - name: Running Tests with IPInfo-Lite DB
        run: |
          unzip -P ${{ secrets.IPINFO_DB_ZIP }} ipinfo_lite.mmdb.zip
          cp ipinfo_lite.mmdb.zip /tmp/ipinfo_lite.mmdb

          bash test/test.sh

          echo 'LOGS:'
          echo ''
          echo '/tmp/haproxy_geoip_backend.log'
          cat /tmp/haproxy_geoip_backend.log

          if [ -f /tmp/haproxy_test_err.log ]
          then
            echo ''
            echo '/tmp/haproxy_test_err.log'
            cat /tmp/haproxy_test_err.log
          fi

          echo ''
          echo '/tmp/haproxy_test.log'
          cat /tmp/haproxy_test.log
        shell: bash
